#---------------------------------------------------#
# EDP 380C.26: Simulation in R
# Lab 5: Introduction to Maximum Likelihood
#
# Add simulation functions from Lab 4 here...
# Use the same set up for each function. E.g.:
#
##' Discuss what this function does...
##'
##' @param y Describe this parameter here...
##' @return Describe what this returns...

